trigger:
  branches:
    include:
      - main
  paths:
    include:
      - '*'
      
stages:
  - stage: DeployACI
    displayName: Deploy to ACI
    jobs:
      - job: Deploy
        displayName: Deploy to ACI
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - task: Docker@2
            displayName: 'Build Docker image'
            inputs:
              repository: 'myimage'
              command: 'build'
              Dockerfile: '$(Build.SourcesDirectory)/CI-CD/Dockerfile'
