trigger:
  branches:
    include:
      - main

stages:
  - stage: BuildAndPush
    displayName: Build Image and push to ECR
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - task: Docker@2
            displayName: 'Build Docker image'
            inputs:
              repository: $(Build.Repository.Name)
              command: 'build'
              Dockerfile: '$(Build.SourcesDirectory)/CI-CD/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)/'
              tags: $(Build.BuildId)

          - task: Docker@2
            displayName: 'Push an image'
            inputs:
              containerRegistry: 'docker_hub'
              repository: 'kaushikruth123/$(Build.Repository.Name)'
              command: 'push'
              tags: $(Build.BuildId)
          # kaushikruth123/devopsproject
          # - task: AmazonWebServices.aws-vsts-tools.ECRPushImage.ECRPushImage@1
          #   displayName: 'Push built image to AWS ECR'
          #   inputs:
          #     awsCredentials: 'aws_resource_manager'
          #     regionName: 'US-east-1'
          #     sourceImageName: mycontainer
          #     repositoryName: devopsproject
          #     sourceImageTag: 'latest'
          #     pushTag: '$(Build.BuildId)'