trigger:
  branches:
    include:
      - main

stages:
  - stage: BuildAndPush
    displayName: Build Image and push to ECR
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - task: Docker@2
            displayName: 'Build Docker image'
            inputs:
              repository: 'mycontainer'
              command: 'build'
              Dockerfile: '$(Build.SourcesDirectory)/CI-CD/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)/'
              tags: 'latest'

          - task: Docker@0
            displayName: 'Push an image'
            inputs:
              containerregistrytype: 'Container Registry'
              dockerRegistryConnection: 'docker_hub'
              action: 'Push an image'
              imageName: $(Build.Repository.Name):$(Build.BuildId)
              
          # - task: AmazonWebServices.aws-vsts-tools.ECRPushImage.ECRPushImage@1
          #   displayName: 'Push built image to AWS ECR'
          #   inputs:
          #     awsCredentials: 'aws_resource_manager'
          #     regionName: 'US-east-1'
          #     sourceImageName: mycontainer
          #     repositoryName: devopsproject
          #     sourceImageTag: 'latest'
          #     pushTag: '$(Build.BuildId)'