trigger:
  branches:
    include:
      - main

stages:
  -stage: DeployACI
  -displayName: Deploy to ACI
  jobs:
    - job: Deploy
      displayName: Deploy to ACI
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - checkout: self
        - task: Docker@2
          displayName: 'Build and Push Docker image'
          inputes:
            containerRegistry: 'myacr'
            repository: 'myimage'
            command: 'buildAndPush'
            Dockerfile: '$(Build.SourcesDirectory)/CI-CD/Dockerfile'
            tags: |
            $(Build.BuildId)
            latest
        - task: AzureCLI@2
            displayName: 'Deploy to ACI'
          inputs:
              azureSubscription: 'myazureconnection'  # Replace with your Azure subscription connection name
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az container create --resource-group myresourcegroup --name mycontainer --image myacr.azurecr.io/myimage:$(Build.BuildId) --dns-name-label mydnslabel --ports 80
