trigger:
  branches:
    include:
      - main
      
stages:
  - stage: BuildImage
    displayName: Building Image
    jobs:
      - job: Deploy
        displayName: Building Image
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - task: Docker@2
            displayName: 'Build Docker image'
            inputs:
              repository: 'myimage'
              command: 'build'
              Dockerfile: '$(Build.SourcesDirectory)/CI-CD/Dockerfile'
              buildContext: $(Build.SourcesDirectory)